### ISSUE TITLE
IndexOutOfBoundsException when trying to grab fee amount

### ISSUE THREAD

**Issue by rchaing-figure** [provenance-io/event-stream#40]
## Summary of Bug

Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 0
	at java.base/java.util.Collections$EmptyList.get(Collections.java:4483)
	at cosmos.tx.v1beta1.TxOuterClass$Fee.getAmount(TxOuterClass.java:11037)
	at io.provenance.eventstream.stream.models.extensions.ExtensionsKt.txData(Extensions.kt:52)
	at io.provenance.eventstream.stream.EventStream$toStreamBlock$txErrors$1.invoke(EventStream.kt:205)
	at io.provenance.eventstream.stream.EventStream$toStreamBlock$txErrors$1.invoke(EventStream.kt:205)
	at io.provenance.eventstream.stream.models.extensions.ExtensionsKt.txErroredEvents(Extensions.kt:98)
	at io.provenance.eventstream.stream.EventStream.toStreamBlock(EventStream.kt:205)
	at io.provenance.eventstream.stream.EventStream.access$toStreamBlock(EventStream.kt:56)
	at io.provenance.eventstream.stream.EventStream$queryBlocks$$inlined$map$1$2.emit(Collect.kt:137)
	at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:15)
	at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:15)
	at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:77)
	at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:59)
	at kotlinx.coroutines.flow.FlowKt__BuildersKt$asFlow$$inlined$unsafeFlow$3.collect(SafeCollector.common.kt:115)
	at kotlinx.coroutines.flow.FlowKt__CollectKt.emitAll(Collect.kt:132)
	at kotlinx.coroutines.flow.FlowKt.emitAll(Unknown Source)
	at io.provenance.eventstream.stream.clients.TendermintBlockFetcher$getBlocks$$inlined$transform$1$1.emit(Collect.kt:136)
	at io.provenance.eventstream.stream.clients.TendermintBlockFetcher$getBlocks$$inlined$transform$1$1$1.invokeSuspend(Unknown Source)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

## Version

0.5.0

## Steps to Reproduce

At about around block 1140081 this exception occurs. - testnet
____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by wbaker-figure** [comment]
closed by #41
